# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_drivers', models.CharField(max_length=255)),
                ('seats_available', models.CharField(max_length=255)),
                ('destinations', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('misc_descriptions', models.CharField(max_length=255)),
                ('departure_time', models.CharField(max_length=255)),
            ],
        ),
    ]
